# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
          echo version=${{ github.sha }} >>src/main/resources/hellospring.properties
          echo createTime=`date +%Y%m%d_%H%M` >>src/main/resources/hellospring.properties
          mvn -B package --file pom.xml
          cp target/scim2-0.0.1-SNAPSHOT.jar disk/scim2-0.0.1-SNAPSHOT.jar
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.aliyun_username }}
        password: ${{ secrets.aliyun_key }}
    - name: Docker build&push
      run: |
        docker build . -t registry-vpc.cn-hangzhou.aliyuncs.com/arlandingzone/landingzone:${{ github.sha }}
        docker push registry-vpc.cn-hangzhou.aliyuncs.com/arlandingzone/landingzone${{ github.sha }}
        docker images
        cat kubernetes/deploy.yaml | sed -e "s/\${version}/${{ github.sha }}/" > kubernetes/tmp.yaml